/**
 * SSOT: Component Catalog
 *
 * UI Core Component 카탈로그의 단일 정본(SSOT)
 * [불변 규칙] 페이지/피처는 SSOT를 소비만 함. 새 컴포넌트는 SSOT에 먼저 추가
 *
 * 참조 문서: docu/SSOT_UI_DESIGN.md E장
 */

/**
 * 컴포넌트 분류
 */
export const COMPONENT_CATEGORY = {
  PRIMITIVE: 'primitive',
  COMPOSITE: 'composite',
  PATTERN: 'pattern',
  LAYOUT: 'layout',
} as const;

export type ComponentCategory = typeof COMPONENT_CATEGORY[keyof typeof COMPONENT_CATEGORY];

/**
 * Primitive 컴포넌트 목록
 * 기본 UI 요소 (버튼, 입력, 배지 등)
 */
export const PRIMITIVE_COMPONENTS = {
  BUTTON: 'Button',
  INPUT: 'Input',
  TEXTAREA: 'Textarea',
  SELECT: 'Select',
  CHECKBOX: 'Checkbox',
  RADIO: 'Radio',
  SWITCH: 'Switch',
  BADGE: 'Badge',
  AVATAR: 'Avatar',
  SPINNER: 'Spinner',
  SKELETON: 'Skeleton',
  AITOGGLE: 'AIToggle',
  DATEPICKER: 'DatePicker',
} as const;

/**
 * Composite 컴포넌트 목록
 * 여러 Primitive 조합 (카드, 모달, 테이블 등)
 */
export const COMPOSITE_COMPONENTS = {
  CARD: 'Card',
  MODAL: 'Modal',
  DRAWER: 'Drawer',
  DATATABLE: 'DataTable',
  FORMFIELD: 'FormField',
  FORMFIELD_LAYOUT: 'FormFieldLayout',
  TOOLTIP: 'Tooltip',
  POPOVER: 'Popover',
  TOAST: 'Toast',
  PAGINATION: 'Pagination',
  TABS: 'Tabs',
  ACCORDION: 'Accordion',
  SEARCHBAR: 'SearchBar',
  TABLECARDVIEW: 'TableCardView',
  SPLITTABLELAYOUT: 'SplitTableLayout',
  STATSCARDLAYOUT: 'StatsCardLayout',
} as const;

/**
 * Pattern 컴포넌트 목록
 * 특정 패턴 구현 (페이지 헤더, 액션 바 등)
 */
export const PATTERN_COMPONENTS = {
  PAGE_HEADER: 'PageHeader',
  BOTTOM_ACTION_BAR: 'BottomActionBar',
  CONTEXT_RECOMMENDATION_BANNER: 'ContextRecommendationBanner',
  NOTIFICATION_CARD_LAYOUT: 'NotificationCardLayout',
  LIST_CARD_LAYOUT: 'ListCardLayout',
  ACTION_HEADER: 'ActionHeader',
  ACTION_BUTTON_GROUP: 'ActionButtonGroup',
  ICON_BUTTON_GROUP: 'IconButtonGroup',
  RIGHT_LAYER_MENU: 'RightLayerMenu',
  RIGHT_LAYER_MENU_LAYOUT: 'RightLayerMenuLayout',
} as const;

/**
 * Layout 컴포넌트 목록
 * 레이아웃 구조 (컨테이너, 그리드, 사이드바 등)
 */
export const LAYOUT_COMPONENTS = {
  CONTAINER: 'Container',
  GRID: 'Grid',
  SIDEBAR_LAYOUT: 'SidebarLayout',
  APP_LAYOUT: 'AppLayout',
  HEADER: 'Header',
  SIDEBAR: 'Sidebar',
  ERROR_BOUNDARY: 'ErrorBoundary',
} as const;

/**
 * 컴포넌트 분류 맵
 */
export const COMPONENT_CATEGORY_MAP: Record<string, ComponentCategory> = {
  // Primitive
  [PRIMITIVE_COMPONENTS.BUTTON]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.INPUT]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.TEXTAREA]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.SELECT]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.CHECKBOX]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.RADIO]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.SWITCH]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.BADGE]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.AVATAR]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.SPINNER]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.SKELETON]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.AITOGGLE]: COMPONENT_CATEGORY.PRIMITIVE,
  [PRIMITIVE_COMPONENTS.DATEPICKER]: COMPONENT_CATEGORY.PRIMITIVE,

  // Composite
  [COMPOSITE_COMPONENTS.CARD]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.MODAL]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.DRAWER]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.DATATABLE]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.FORMFIELD]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.FORMFIELD_LAYOUT]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.TOOLTIP]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.POPOVER]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.TOAST]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.PAGINATION]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.TABS]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.ACCORDION]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.SEARCHBAR]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.TABLECARDVIEW]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.SPLITTABLELAYOUT]: COMPONENT_CATEGORY.COMPOSITE,
  [COMPOSITE_COMPONENTS.STATSCARDLAYOUT]: COMPONENT_CATEGORY.COMPOSITE,

  // Pattern
  [PATTERN_COMPONENTS.PAGE_HEADER]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.BOTTOM_ACTION_BAR]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.CONTEXT_RECOMMENDATION_BANNER]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.NOTIFICATION_CARD_LAYOUT]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.LIST_CARD_LAYOUT]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.ACTION_HEADER]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.ACTION_BUTTON_GROUP]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.ICON_BUTTON_GROUP]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.RIGHT_LAYER_MENU]: COMPONENT_CATEGORY.PATTERN,
  [PATTERN_COMPONENTS.RIGHT_LAYER_MENU_LAYOUT]: COMPONENT_CATEGORY.PATTERN,

  // Layout
  [LAYOUT_COMPONENTS.CONTAINER]: COMPONENT_CATEGORY.LAYOUT,
  [LAYOUT_COMPONENTS.GRID]: COMPONENT_CATEGORY.LAYOUT,
  [LAYOUT_COMPONENTS.SIDEBAR_LAYOUT]: COMPONENT_CATEGORY.LAYOUT,
  [LAYOUT_COMPONENTS.APP_LAYOUT]: COMPONENT_CATEGORY.LAYOUT,
  [LAYOUT_COMPONENTS.HEADER]: COMPONENT_CATEGORY.LAYOUT,
  [LAYOUT_COMPONENTS.SIDEBAR]: COMPONENT_CATEGORY.LAYOUT,
  [LAYOUT_COMPONENTS.ERROR_BOUNDARY]: COMPONENT_CATEGORY.LAYOUT,
};

/**
 * 컴포넌트 분류 조회
 */
export function getComponentCategory(componentName: string): ComponentCategory | undefined {
  return COMPONENT_CATEGORY_MAP[componentName];
}

/**
 * 컴포넌트가 UI Core에 존재하는지 확인
 */
export function isUICoreComponent(componentName: string): boolean {
  return componentName in COMPONENT_CATEGORY_MAP;
}

/**
 * 컴포넌트 사용 권장 사항 조회
 */
export function getComponentRecommendation(useCase: string): string | undefined {
  const recommendations: Record<string, string> = {
    // 페이지 구조
    '전체 앱 레이아웃': LAYOUT_COMPONENTS.APP_LAYOUT,
    '페이지 컨테이너': LAYOUT_COMPONENTS.CONTAINER,
    '페이지 헤더': PATTERN_COMPONENTS.PAGE_HEADER,
    '사이드바': LAYOUT_COMPONENTS.SIDEBAR,
    '글로벌 헤더': LAYOUT_COMPONENTS.HEADER,

    // 폼 입력
    '텍스트 입력': PRIMITIVE_COMPONENTS.INPUT,
    '긴 텍스트 입력': PRIMITIVE_COMPONENTS.TEXTAREA,
    '선택 드롭다운': PRIMITIVE_COMPONENTS.SELECT,
    '날짜 선택': PRIMITIVE_COMPONENTS.DATEPICKER,
    '체크박스': PRIMITIVE_COMPONENTS.CHECKBOX,
    '라디오 버튼': PRIMITIVE_COMPONENTS.RADIO,
    '스위치': PRIMITIVE_COMPONENTS.SWITCH,
    'AI 토글': PRIMITIVE_COMPONENTS.AITOGGLE,

    // 데이터 표시
    '카드': COMPOSITE_COMPONENTS.CARD,
    '테이블': COMPOSITE_COMPONENTS.DATATABLE,
    '배지': PRIMITIVE_COMPONENTS.BADGE,
    '아바타': PRIMITIVE_COMPONENTS.AVATAR,
    '툴팁': COMPOSITE_COMPONENTS.TOOLTIP,
    '검색 바': COMPOSITE_COMPONENTS.SEARCHBAR,

    // 액션/인터랙션
    '버튼': PRIMITIVE_COMPONENTS.BUTTON,
    '모달': COMPOSITE_COMPONENTS.MODAL,
    '드로어': COMPOSITE_COMPONENTS.DRAWER,
    '토스트': COMPOSITE_COMPONENTS.TOAST,
    '페이지네이션': COMPOSITE_COMPONENTS.PAGINATION,
  };

  return recommendations[useCase];
}

